-- public.cos_connections definition

-- Drop table

-- DROP TABLE public.cos_connections;

CREATE TABLE public.cos_connections (
                                        created_at int8 NULL,
                                        id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                        accesskey varchar(255) NULL,
                                        apikey varchar(255) NULL,
                                        authendication_type varchar(255) NULL,
                                        bucket_id varchar(255) NULL,
                                        bucket_name varchar(255) NULL,
                                        bucketurl varchar(255) NULL,
                                        cos_name varchar(255) NOT NULL,
                                        created_by varchar(255) NULL,
                                        department_id varchar(255) NOT NULL,
                                        env_type varchar(255) NOT NULL,
                                        "location" varchar(255) NULL,
                                        secretkey varchar(255) NULL,
                                        service_instance_id varchar(255) NULL,
                                        storage_location varchar(255) NULL,
                                        storage_type varchar(255) NULL,
                                        CONSTRAINT cos_connections_pkey PRIMARY KEY (id)
);


-- public.db_connections definition

-- Drop table

-- DROP TABLE public.db_connections;

CREATE TABLE public.db_connections (
                                       id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                       connection_name varchar(255) NOT NULL,
                                       dburi varchar(255) NULL,
                                       department varchar(255) NOT NULL,
                                       environment varchar(255) NOT NULL,
                                       "password" varchar(255) NULL,
                                       type_of_database varchar(255) NOT NULL,
                                       username varchar(255) NULL,
                                       vault_path varchar(255) NULL,
                                       vault_role varchar(255) NULL,
                                       CONSTRAINT db_connections_pkey PRIMARY KEY (id)
);


-- public.departments definition

-- Drop table

-- DROP TABLE public.departments;

CREATE TABLE public.departments (
                                    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                    "name" varchar(255) NOT NULL,
                                    CONSTRAINT departments_name_key UNIQUE (name),
                                    CONSTRAINT departments_pkey PRIMARY KEY (id)
);


-- public.job_checkpoints definition

-- Drop table

-- DROP TABLE public.job_checkpoints;

CREATE TABLE public.job_checkpoints (
                                        partition_id int4 NOT NULL,
                                        id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                        job_execution_id int8 NOT NULL,
                                        last_read_offset int8 NOT NULL,
                                        total_rows_processed int8 NOT NULL,
                                        updated_at timestamp(6) NOT NULL,
                                        last_processed_key varchar(255) NULL,
                                        status varchar(255) NULL,
                                        table_name varchar(255) NOT NULL,
                                        CONSTRAINT job_checkpoints_job_execution_id_table_name_partition_id_key UNIQUE (job_execution_id, table_name, partition_id),
                                        CONSTRAINT job_checkpoints_pkey PRIMARY KEY (id)
);


-- public.job_definitions definition

-- Drop table

-- DROP TABLE public.job_definitions;

CREATE TABLE public.job_definitions (
                                        chunk_size int4 NULL,
                                        thread_count int4 NULL,
                                        created_at timestamp(6) NOT NULL,
                                        id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                        updated_at timestamp(6) NULL,
                                        batch_mode varchar(255) NULL,
                                        config_yaml text NOT NULL,
                                        created_by varchar(255) NULL,
                                        description varchar(255) NULL,
                                        job_name varchar(255) NOT NULL,
                                        status varchar(255) NOT NULL,
                                        CONSTRAINT job_definitions_job_name_key UNIQUE (job_name),
                                        CONSTRAINT job_definitions_pkey PRIMARY KEY (id),
                                        CONSTRAINT job_definitions_status_check CHECK (((status)::text = ANY ((ARRAY['CONFIGURED'::character varying, 'RUNNING'::character varying, 'PAUSED'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying])::text[])))
);


-- public.job_requests definition

-- Drop table

-- DROP TABLE public.job_requests;

CREATE TABLE public.job_requests (
                                     created_at int8 NULL,
                                     id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                     "comments" varchar(255) NULL,
                                     config_details text NULL,
                                     department varchar(255) NULL,
                                     job_type varchar(255) NOT NULL,
                                     migration_name varchar(255) NOT NULL,
                                     status varchar(255) NOT NULL,
                                     submitted_by varchar(255) NULL,
                                     CONSTRAINT job_requests_pkey PRIMARY KEY (id)
);


-- public.migration_job definition

-- Drop table

-- DROP TABLE public.migration_job;

CREATE TABLE public.migration_job (
                                      created_at timestamp(6) NULL,
                                      id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                      updated_at timestamp(6) NULL,
                                      job_id varchar(255) NOT NULL,
                                      job_status varchar(255) NULL,
                                      project_id varchar(255) NULL,
                                      source_db_type varchar(255) NULL,
                                      target_db_type varchar(255) NULL,
                                      CONSTRAINT migration_job_job_id_key UNIQUE (job_id),
                                      CONSTRAINT migration_job_pkey PRIMARY KEY (id)
);


-- public.mongo_migration_details definition

-- Drop table

-- DROP TABLE public.mongo_migration_details;

CREATE TABLE public.mongo_migration_details (
                                                completed_at timestamp(6) NULL,
                                                failed_count int8 NULL,
                                                id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                                migrated_count int8 NULL,
                                                source_count int8 NULL,
                                                started_at timestamp(6) NULL,
                                                collection_name varchar(255) NULL,
                                                job_id varchar(255) NOT NULL,
                                                remarks varchar(255) NULL,
                                                status varchar(255) NULL,
                                                CONSTRAINT mongo_migration_details_pkey PRIMARY KEY (id)
);


-- public.roles definition

-- Drop table

-- DROP TABLE public.roles;

CREATE TABLE public.roles (
                              id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                              "name" varchar(255) NOT NULL,
                              CONSTRAINT roles_name_key UNIQUE (name),
                              CONSTRAINT roles_pkey PRIMARY KEY (id)
);


-- public.user_roles definition

-- Drop table

-- DROP TABLE public.user_roles;

CREATE TABLE public.user_roles (
                                   user_id int8 NOT NULL,
                                   "role" varchar(255) NULL
);


-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
                              id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                              role_id int8 NULL,
                              "password" varchar(255) NOT NULL,
                              username varchar(255) NOT NULL,
                              CONSTRAINT users_pkey PRIMARY KEY (id),
                              CONSTRAINT users_username_key UNIQUE (username),
                              CONSTRAINT fkp56c1712k691lhsyewcssf40f FOREIGN KEY (role_id) REFERENCES public.roles(id)
);


-- public.user_departments definition

-- Drop table

-- DROP TABLE public.user_departments;

CREATE TABLE public.user_departments (
                                         department_id int8 NOT NULL,
                                         user_id int8 NOT NULL,
                                         CONSTRAINT user_departments_pkey PRIMARY KEY (department_id, user_id),
                                         CONSTRAINT fke1yilu7bslmau7ojj0n2pu812 FOREIGN KEY (department_id) REFERENCES public.departments(id),
                                         CONSTRAINT fkeklynfw1mm4x2289n61pj0ojn FOREIGN KEY (user_id) REFERENCES public.users(id)
);
-- 1. Insert Departments
INSERT INTO public.departments (name) VALUES
                                          ('Finance'), ('IT'), ('HR'), ('Compliance'), ('Sales'),
                                          ('Marketing'), ('Operations'), ('Legal'), ('R&D'), ('Support');

-- 2. Insert Roles
INSERT INTO public.roles (name) VALUES
                                    ('admin'), ('manager'), ('scheduler'), ('approver');

-- 3. Insert Users
INSERT INTO public.users (username, password, role_id) VALUES
                                                           ('alice_admin', 'hashed_pwd_1', 1),
                                                           ('bob_manager', 'hashed_pwd_2', 2),
                                                           ('charlie_scheduler', 'hashed_pwd_3', 3),
                                                           ('diana_approver', 'hashed_pwd_4', 4),
                                                           ('eve_dev', 'hashed_pwd_5', 2),
                                                           ('frank_fin', 'hashed_pwd_6', 4),
                                                           ('grace_hr', 'hashed_pwd_7', 2),
                                                           ('heidi_comp', 'hashed_pwd_8', 4),
                                                           ('ivan_sales', 'hashed_pwd_9', 3),
                                                           ('judy_ops', 'hashed_pwd_10', 2);

-- 4. Assign Departments to Users
INSERT INTO public.user_departments (user_id, department_id) VALUES
                                                                 (1, 1), (1, 2), -- Admin in Finance & IT
                                                                 (2, 2), (2, 7), -- Manager in IT & Ops
                                                                 (3, 2),         -- Scheduler in IT
                                                                 (4, 4), (4, 8), -- Approver in Compliance & Legal
                                                                 (5, 2), (6, 1), (7, 3), (8, 4), (9, 5), (10, 7);

-- 5. Insert User Roles (Mapping)
INSERT INTO public.user_roles (user_id, role) VALUES
                                                  (1, 'admin'), (2, 'manager'), (3, 'scheduler'), (4, 'approver'),
                                                  (5, 'manager'), (6, 'approver'), (7, 'manager'), (8, 'approver'),
                                                  (9, 'scheduler'), (10, 'manager');

-- 6. Insert COS Connections
INSERT INTO public.cos_connections (cos_name, department_id, env_type, bucket_name)
SELECT 'COS_' || i, (i % 10) + 1, 'PROD', 'bucket_' || i
FROM generate_series(1, 10) AS s(i);

-- 7. Insert DB Connections
INSERT INTO public.db_connections (connection_name, department, environment, type_of_database)
SELECT 'DB_' || i, 'Dept_' || i, 'PROD', 'POSTGRESQL'
FROM generate_series(1, 10) AS s(i);

-- 8. Insert Job Definitions
INSERT INTO public.job_definitions (job_name, config_yaml, status, created_at)
SELECT 'Job_' || i, 'config: data', 'CONFIGURED', NOW()
FROM generate_series(1, 10) AS s(i);

-- 9. Insert Job Requests
INSERT INTO public.job_requests (migration_name, job_type, status)
SELECT 'Mig_' || i, 'FULL', 'PENDING'
FROM generate_series(1, 10) AS s(i);

-- 10. Insert Migration Jobs
INSERT INTO public.migration_job (job_id, job_status, project_id)
SELECT 'JID_' || i, 'RUNNING', 'PROJ_' || i
FROM generate_series(1, 10) AS s(i);

-- 11. Insert Mongo Migration Details
INSERT INTO public.mongo_migration_details (job_id, status)
SELECT 'JID_' || i, 'STARTED'
FROM generate_series(1, 10) AS s(i);

-- 12. Insert Job Checkpoints
INSERT INTO public.job_checkpoints (job_execution_id, table_name, partition_id, last_read_offset, total_rows_processed, updated_at)
SELECT i, 'table_' || i, 0, 0, 0, NOW()
FROM generate_series(1, 10) AS s(i);